### ISSUE TITLE
where does default settings in config parameter come from?

### ISSUE THREAD

**Issue by MassMessage** [oklas/react-app-rewire-alias#1]
where does default settings in `config` parameter came from? a file or what? can i override it?

i mean the config passed as callback in this case:
```javascript
const { alias, configPaths } = require('react-app-rewire-alias');

module.exports = function override(config) {
    //console.log('config = ', config)
    return alias(configPaths('./tsconfig.paths.json'))(config);
};
```

**Comment by oklas** [comment]
Hi @MassMessage,

The parameter `config` is config for webpack created by `react-scripts`. You can modify it in runtime. Check [how-it-works](https://github.com/oklas/react-app-alias/blob/master/docs/how-it-works.md

What is the page where from you get this package? This package is renamed to [react-app-alias](https://github.com/oklas/react-app-alias). Check [migration guide](https://github.com/oklas/react-app-alias/blob/master/docs/migration.md) Its possible the link on referral page need to bo chamged, so users can get right place.

Thanks

**Comment by oklas** [comment]
Hi @MassMessage,

The parameter `config` is config for webpack created by `react-scripts`. You can modify it in runtime. Check [how-it-works](https://github.com/oklas/react-app-alias/blob/master/docs/how-it-works.md)

What is the page where from you get this package? This package is renamed to [react-app-alias](https://github.com/oklas/react-app-alias). Check [migration guide](https://github.com/oklas/react-app-alias/blob/master/docs/migration.md) Its possible the link on referral page need to bo chamged, so users can get right place.

Thanks
