### ISSUE TITLE
Cannot resolve `eslint-loader`

### ISSUE THREAD

**Issue by cliffordfajardo** [oklas/react-app-rewire-alias#19]
## Description
When I use the `aliasDangerous` method I am getting the following error:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'eslint-loader'
Require stack:
```

## Scenario
I've created a new `create-react-app` and am using `react-app-rewired`.
I'm working in a mono-repo style repository that looks like this:

```
root
    backend
        src
    shared
        src
    web
        src
```
The reason I am using the dangerous option is that I need the `/web` codebase to import from shared which contains some utility javascript files.

When I commented out these 2 lines inside of the `aliasDangerous` file the code worked
![image](https://user-images.githubusercontent.com/6743796/109375177-84d22680-786f-11eb-964f-311c2a13ac18.png)

I was wondering what  the purpose of importing `eslint-loader` is?
If the `aliasDangerous.js` file has this, why doesnt the non dangerous version code have it ?

**Comment by cliffordfajardo** [comment]
It seems eslint-loader is deprecated now
- https://github.com/gsoft-inc/craco/issues/205#issuecomment-715894250

**Comment by oklas** [comment]
Thanks 👍,  try version 1.0.1

**Comment by cliffordfajardo** [comment]
@oklas  - this fixed my problem - thank you!
