### ISSUE TITLE
alias(configPaths()) isn't working for me

### ISSUE THREAD

**Issue by MassMessage** [oklas/react-app-rewire-alias#2]
this is not working for me:

```
module.exports = function override(config)
{
    return alias(configPaths('./tsconfig.paths.json'))(config);
}
```

I get the error:

> [0] Module not found: Can't resolve '@Shared/ChannelName' in 'C:\Users\jckj33\Desktop\merge\Newton\src\components'

but this is working:

```
module.exports = function override(config)
{
    config.resolve = config.resolve || {};
    config.resolve.alias = config.resolve.alias || {};

    Object.assign(config.resolve.alias, {
        '@Shared': path.resolve(__dirname, 'src/shared')
    });

    return config
};
```

tsconfig.paths.json is defined like this:

```
{
    "compilerOptions":
    {
        "baseUrl": "src",
        "paths": {
            "@Shared/*": ["shared/*"]
        }
    }
}
```

What am I missing?

**Comment by MassMessage** [comment]
> this is not working for me:
> 
> ```
> module.exports = function override(config)
> {
>     return alias(configPaths('./tsconfig.paths.json'))(config);
> }
> ```
> 
> I get the error:
> 
> > [0] Module not found: Can't resolve '@Shared/ChannelName' in 'C:\Users\jckj33\Desktop\merge\Newton\src\components'
> 
> but this is working:
> 
> ```
> module.exports = function override(config)
> {
>     config.resolve = config.resolve || {};
>     config.resolve.alias = config.resolve.alias || {};
> 
>     Object.assign(config.resolve.alias, {
>         '@Shared': path.resolve(__dirname, 'src/shared')
>     });
> 
>     return config
> };
> ```
> 
> tsconfig.paths.json is defined like this:
> 
> ```
> {
>     "compilerOptions":
>     {
>         "baseUrl": "src",
>         "paths": {
>             "@Shared/*": ["shared/*"]
>         }
>     }
> }
> ```
> 
> What am I missing?

I just found out  alias(configPaths()) isn't considering the `baseUrl` in `tsconfig.paths.json`a file when generating the paths so give the paths in the orginal poster, it is generating:

```
    alias: {
      'react-native': 'react-native-web',
       '@Shared': 'C:\\Users\\jckj33\\Desktop\\merge\\Newton\\shared'
     }
```

instead of:

```
    alias: {
       'react-native': 'react-native-web',
       '@Shared': 'C:\\Users\\jckj33\\Desktop\\merge\\Newton\\src\\shared'
     }
```


note it's missing the `src` folder as defined in the `baseUrl` in the `tsconfig.paths.json` file. Any workaround for this to keep using `alias(configPaths())`

**Comment by oklas** [comment]
Hi @MassMessage

Yesterday I wrote you:

> What is the page where from you get this package? This package is renamed to [react-app-alias](https://github.com/oklas/react-app-alias). Check [migration guide](https://github.com/oklas/react-app-alias/blob/master/docs/migration.md) Its possible the link on referral page need to bo chamged, so users can get right place.

On the top of readme also is message about rename. Can I do something else to make it more noticeable?

This your issue is moved to [react-app-alias#69](https://github.com/oklas/react-app-alias/issues/69). Please let us continue discussing and solve the issue on that page.

Thanks
