### ISSUE TITLE
 warning : compilerOptions.paths must not be set (aliased imports are not supported)

### ISSUE THREAD

**Issue by chrys-exaucet** [oklas/react-app-rewire-alias#27]
I am still getting this weird warning although it is supposed to have been fixed. Am I missing something in my config?

````
$ yarn test
yarn run v1.22.10
$ react-app-rewired test -- --config=jest.config.ts
The following changes are being made to your tsconfig.json file:
  - compilerOptions.paths must not be set (aliased imports are not supported)

````

````json

// package.json

  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test -- --config=jest.config.ts",
    "eject": "react-scripts eject"
  },
````

````json
// tsconfig.json

{
  "extends": "./tsconfig.paths.json",
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src",
    "../../shared"
  ]
}


````

````json


// tsconfig.paths.json

{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@shared/*": ["../../shared/*"],
      "@app/*": ["src/*"]
    }
  }
}


````

````js

// config-overrides.js

const { alias, configPaths } = require('react-app-rewire-alias');

module.exports = function override(config) {
  alias(configPaths('./tsconfig.paths.json'))(config);

  return config;
};

````

##  dependencies

 react-app-rewire-alias@1.0.3
 react-app-rewired@2.1.8
 react@17.0.2
yarn@1.22.10

 ##  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 2.16 GB / 15.85 GB

**Comment by oklas** [comment]
Just notices that you are extending `tsconfig.json` by `tsconfig.paths.json`. And same time you are extending `tsconfig.paths.json` by some another `../../tsconfig.json`. That is strange currently is not clear what that may causes. Also as whole config.

I would suggests step-by-step approach with small changes from worked config to problem config. Get worked project (from example dir) as a base and go with small modifications to your current config. Make a commit for each worked step. When problem change is arriving do a commit and create issue with reference to a repo with problem config.

**Comment by oklas** [comment]
Feel free to add more info or create new issue
