### ISSUE TITLE
Error in monorepo setup: react-app-rewire-alias:configPaths: array expected for paths

### ISSUE THREAD

**Issue by hirikarate** [oklas/react-app-rewire-alias#45]
I'm using
- "react-scripts": "5.0.0"
- "react-app-rewire-alias": "1.1.5",
- "react-app-rewired": "2.1.8"

with a **monorepo setup with Yarn Workspace** and encountering this error:
```
react-app-rewire-alias:configPaths: array expected for paths, specify ../../../tsconfig.json instead of G:\my-project\packages\apps\react-web\tsconfig.json for configPaths()
```

This is my root `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es5",
    // truncated for brevity
    "paths": {
      "@myway/moduleOne/*": ["./packages/libs/moduleOne/src/*"],
      "@myway/moduleTwo/*": ["./packages/libs/moduleTwo/src/*"]
    }
  },
  "include": [
    "packages"
  ]
}
```

This is my module `tsconfig.json`
```json
{
   "extends": "../../../tsconfig.json",
   "compilerOptions": {
       "isolatedModules": true
    }
}
```

My `config-overrides.js`
```javascript
const tsPaths = configPaths('../../../tsconfig.json');

Object.entries(tsPaths).forEach(([key, value]) => {
   tsPaths[key] = path.resolve(__dirname, `../../../${value}`);
});

module.exports = aliasDangerous(tsPaths);
// truncated for brevity
```

This setup **worked** with "react-app-rewire-alias@~1.0" but now it has the mentioned error.

I think it's because of the check at [index.js#L116](https://github.com/oklas/react-app-rewire-alias/blob/master/src/index.js#L116)
I trying this fix locally and it works:
```javascript
if(conf.compilerOptions.paths && typeof conf.compilerOptions.paths !== 'object')
    throw Error(`
      react-app-rewire-alias:configPaths: array expected for paths${extmsg}`)
```

IMO it's OK for module `tsconfig.ts` not to have paths declare explicitly because it can inherit from the root one.

**Comment by oklas** [comment]
This part of code was changed at #43 and was not released at time when you was worked on. It is released at 1.1.6. And it has some another behavior so your modification may be not actual or different. 

And some more. Even if it will be applied, how it will be worked at line [index.js#L126](https://github.com/oklas/react-app-rewire-alias/blob/master/src/index.js#L126) and some else where null is not expected.

Check also example in doc. The main file is `tsconfig.json` but for plugin setting specified not that but `tsconfig.paths.json` instead - may be you need to use approach like that.
