### ISSUE TITLE
`expandPluginsScope()` should preserve `ModuleScopePlugin.allowedFiles`

### ISSUE THREAD

**Issue by LoneRifle** [oklas/react-app-rewire-alias#46]
react-scripts@5 introduces webpack@5, which no longer has built-in shims. Thus, react-scripts explicitly supplies the shims via ModuleScopePlugin, which `expandPluginsScope()` manipulates.

This function should hence preserve the shim entries so that compilation can continue.

### Footnotes 
Setup:
- react-app-rewire-alias@1.1.6
- react-app-rewired@2.1.8
- react-scripts@5.0.0

This issue was investigated using the following config files:
https://github.com/opengovsg/askgovsg/blob/dependabot/npm_and_yarn/client/react-scripts-5.0.0/client/config-overrides.js
https://github.com/opengovsg/askgovsg/blob/dependabot/npm_and_yarn/client/react-scripts-5.0.0/client/tsconfig.paths.json

The build fails with webpack (via react-scripts) complaining that it no longer can find packages in the project's `node_modules`:
https://github.com/opengovsg/askgovsg/runs/4577986959?check_suite_focus=true#step:11:14

**Comment by oklas** [comment]
Thanks 🙏. Released in 1.1.7
