### ISSUE TITLE
CRA 4.0 support?

### ISSUE THREAD

**Issue by xinghul** [oklas/react-app-rewire-alias#9]
Hi there, not entirely sure what's happening, I tried to upgrade to CRA 4.0, but I got this error:
```bash
node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:241
      appTsConfig.compilerOptions[option] = value;
                                          ^

TypeError: Cannot add property paths, object is not extensible
```

**Comment by xinghul** [comment]
nvm, this is irrelevant.

**Comment by nvt1995-dev** [comment]
Hello, i'm getting the same error. Did you succeed to resolve it? Thank you!

**Comment by oklas** [comment]
Hi, @xinghul, why did you closed as irrelevant? Write your thoughts or problem more detailed to let people know what they can experienced and how to solve. It save time for many people.

Hi, @nvt1995-dev also provide your experience here.

Also relevant issue: [create-react-app #9429](https://github.com/facebook/create-react-app/issues/9429) - I will see if will have time.

Also use create-react-app 4.0 will impossible without this pull [create-react-app #9921](https://github.com/facebook/create-react-app/pull/9921) - int is merged but not released - so wait when any create-react-app version above 4.0 will be released (or get patch manually using patch-package).

It is actual - so I reopen issue

**Comment by xinghul** [comment]
@oklas I digged into the code and realized it's an issue with CRA 4.0.

**Comment by oklas** [comment]
The pull [create-react-app #9921](https://github.com/facebook/create-react-app/pull/9921) is merged but not released yet. Currently that is the only thing is blocking to work.

Here the commit 600ffb4 (on example project) to demonstrate how to apply manually patch for  9921 using [patch-package](https://www.npmjs.com/package/patch-package). 

Form outside of root TS does not see libraries, but JS works. In the root (near src) TS works.

Docs also actualised to simplify usage.

**Comment by oklas** [comment]
Currently problem does not concern `react-app-rewire-alias` and it will be worked with next release of `create-react-app` (or with previous) or with mentioned above patch. So I close this for now. Anyone feel free to write or reopen if any.
